export const ADD_RULE = 'ADD_RULE';
export const ADD_RULE_GROUP = 'ADD_RULE_GROUP';
export const UPDATE_RULE = 'UPDATE_RULE';
export const UPDATE_RULE_GROUP = 'UPDATE_RULE_GROUP';
export const REMOVE_RULE = 'REMOVE_RULE';
export const REMOVE_RULE_GROUP = 'REMOVE_RULE_GROUP';
export const CALL_VALIDATION_API_SUCCESS = 'CALL_VALIDATION_API_SUCCESS';
export const CALL_VALIDATION_API_FAILURE = 'CALL_VALIDATION_API_FAILURE';
