export const RULE_OP_ADD_RULE = 'RULE_OP_ADD_RULE';
export const RULE_OP_ADD_RULE_GROUP = 'RULE_OP_ADD_RULE_GROUP';
export const RULE_OP_UPDATE_RULE = 'RULE_OP_UPDATE_RULE';
export const RULE_OP_UPDATE_RULE_GROUP = 'RULE_OP_UPDATE_RULE_GROUP';
export const RULE_OP_REMOVE_RULE = 'RULE_OP_REMOVE_RULE';
export const RULE_OP_REMOVE_RULE_GROUP = 'RULE_OP_REMOVE_RULE_GROUP';

export const ADD_ACTION = 'ADD_ACTION';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const REMOVE_ACTION = 'REMOVE_ACTION';
export const REORDER_ACTIONS = 'REORDER_ACTIONS';

export const TEST_RULESET_REQUEST = 'TEST_RULESET_REQUEST';
export const TEST_RULESET_SUCCESS = 'TEST_RULESET_SUCCESS';
export const TEST_RULESET_FAILURE = 'TEST_RULESET_FAILURE';

export const SUBMIT_RULESET_REQUEST = 'SUBMIT_RULESET_REQUEST';
export const SUBMIT_RULESET_SUCCESS = 'SUBMIT_RULESET_SUCCESS';
export const SUBMIT_RULESET_FAILURE = 'SUBMIT_RULESET_FAILURE';

export const FETCH_RULESETS_SUCCESS = 'FETCH_RULESETS_SUCCESS';
export const FETCH_RULESETS_REQUEST = 'FETCH_RULESETS_REQUEST';
export const FETCH_RULESETS_FAILURE = 'FETCH_RULESETS_FAILURE';

export const TOGGLE_RULESET_ACTIVE_REQUEST = 'TOGGLE_RULESET_ACTIVE_REQUEST';
export const TOGGLE_RULESET_ACTIVE_SUCCESS = 'TOGGLE_RULESET_ACTIVE_SUCCESS';
