export const RULE_OP_ADD_RULE = 'RULE_OP_ADD_RULE';
export const RULE_OP_ADD_RULE_GROUP = 'RULE_OP_ADD_RULE_GROUP';
export const RULE_OP_UPDATE_RULE = 'RULE_OP_UPDATE_RULE';
export const RULE_OP_UPDATE_RULE_GROUP = 'RULE_OP_UPDATE_RULE_GROUP';
export const RULE_OP_REMOVE_RULE = 'RULE_OP_REMOVE_RULE';
export const RULE_OP_REMOVE_RULE_GROUP = 'RULE_OP_REMOVE_RULE_GROUP';

export const ADD_ACTION = 'ADD_ACTION';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const REMOVE_ACTION = 'REMOVE_ACTION';
export const REORDER_ACTIONS = 'REORDER_ACTIONS';

export const TEST_RULESET_REQUEST = 'TEST_RULESET_REQUEST';
export const TEST_RULESET_SUCCESS = 'TEST_RULESET_SUCCESS';
export const TEST_RULESET_FAILURE = 'TEST_RULESET_FAILURE';
